READ .ONE
JG START
.ONE 1
.ZERO 0
.MINUS -1
.ITERATIONS_ACCESS .ITERATIONS
.ITERATIONS 100
.EXCLAMATION 33
START
    READ .MINUS
    COPY R1 R0
    READ .ITERATIONS_ACCESS
    LOAD R2 R0
    READ .EXCLAMATION
    LOOP
        SYS PUTC
        ADD R2 R1
        JG LOOP
SYS HALT